### PR TITLE
Revert "chore: update IV path structures"

### PR DESCRIPTION
**Pull request by CikiMomogi**
This reverts commit 9bf02432db0cfa2ba6f69f6b7d57fa7a15547e33.

Reason: https://github.com/grammyjs/website/pull/655#issuecomment-1458162738

### CODE REVIEW

**Comment by KnorpelSenf** [comment]
@roj1512 are the rules still outdated? I can adjust them if necessary

**Comment by roj1512** [comment]
@CikiMomogi Sorry, I wrongly said revert. I think you need to add zh alongside id and es.

**Comment by roj1512** [comment]
@KnorpelSenf I don’t know. Outdated like how?

**Comment by KnorpelSenf** [comment]
They don't apply to all languages, do they?

**Review by roj1512 — APPROVED** [review]
LGTM. Thank you so much!

**Comment by roj1512** [comment]
@KnorpelSenf I still don’t understand.

**Comment by KnorpelSenf** [comment]
Don't worry. I checked myself. IV rules don't apply for ZH yet. I'll sync.

**Comment by KnorpelSenf** [comment]
Done

**Pull request merged**
